### ISSUE TITLE
Пушка

### ISSUE THREAD

**Issue by Ainoss** [Striz-lab/infa_2019_strizhak#7]
Задача проработана не очень хорошо, есть как странные решения, так и явные баги.
Странно, что vy для шариков и таргетов обрабатывается по разному. Остальные детали - в комментариях к коммиту.

Рекомендую переработать задачу, время еще есть.

**Comment by Striz-lab** [comment]
Исправил странные решения и убрал баг, возможно, не лучшим образом, но теперь его быть не должно). К тому же, теперь программа разделена на модули

**Comment by Ainoss** [comment]
Отличная работа, стало лучше!
Но на самом деле решение могло быть значительно проще, производить удаление шариков с помощью вспомогательного массива delit следовало снаружи цикла по balls и обязательно в обратном порядке (для того что бы индексы не съезжали).
Но так тоже работает, хотя и немного костыльно :)
Принято
